"""criacao_inicial

Revision ID: 6a133f1c0ddc
Revises: 
Create Date: 2025-06-10 04:37:06.449540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a133f1c0ddc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('culturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_culturas_id'), 'culturas', ['id'], unique=False)
    op.create_table('produtores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('documento', sa.String(length=18), nullable=False),
    sa.Column('tipo_documento', sa.String(length=4), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documento')
    )
    op.create_index(op.f('ix_produtores_id'), 'produtores', ['id'], unique=False)
    op.create_table('fazendas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cidade', sa.String(), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.Column('area_total', sa.Float(), nullable=False),
    sa.Column('area_agricultavel', sa.Float(), nullable=False),
    sa.Column('area_vegetacao', sa.Float(), nullable=False),
    sa.Column('produtor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['produtor_id'], ['produtores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fazendas_id'), 'fazendas', ['id'], unique=False)
    op.create_table('safras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ano_inicio', sa.Date(), nullable=False),
    sa.Column('ano_fim', sa.Date(), nullable=False),
    sa.Column('fazenda_id', sa.Integer(), nullable=False),
    sa.Column('cultura_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cultura_id'], ['culturas.id'], ),
    sa.ForeignKeyConstraint(['fazenda_id'], ['fazendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safras_id'), 'safras', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_safras_id'), table_name='safras')
    op.drop_table('safras')
    op.drop_index(op.f('ix_fazendas_id'), table_name='fazendas')
    op.drop_table('fazendas')
    op.drop_index(op.f('ix_produtores_id'), table_name='produtores')
    op.drop_table('produtores')
    op.drop_index(op.f('ix_culturas_id'), table_name='culturas')
    op.drop_table('culturas')
    # ### end Alembic commands ###
